## Gradients

In [1]:
import numpy as np
import theano
import theano.tensor as T

In [5]:
x = T.dscalar('x')
y = x ** 2
grad_y = T.grad(y, x)

f1 = theano.function([x], grad_y)
f2 = theano.function([x], y)
print f1(4)
print f2(4)

8.0
16.0


In [6]:
g = np.exp(x)
grad_g = T.grad(g, x)
f3 = theano.function([x], grad_g)
print f3(3)

20.0855369232


In [7]:
x = T.dmatrix('x')
s = T.sum(1 / (1 + T.exp(-x)))
grad_s = T.grad(s, x)

logistic = theano.function([x], grad_s)
logistic([[0, 1], [-1, -2]])

array([[ 0.25      ,  0.19661193],
       [ 0.19661193,  0.10499359]])

## Jacobian

In [11]:
x = T.dvector('x')
y = x ** 2
J, updates = theano.scan(lambda i, y, x : T.grad(y[i], x), 
                         sequences=T.arange(y.shape[0]), non_sequences=[y, x])
f = theano.function([x], J, updates=updates)
f([4, 4, 4])

array([[ 8.,  0.,  0.],
       [ 0.,  8.,  0.],
       [ 0.,  0.,  8.]])

In [12]:
#theano.gradient.jacobian()

## Hessian

In [15]:
x = T.dvector('x')
y = x ** 2
cost = y.sum()
grad_y = T.grad(cost, x)
H, updates = theano.scan(lambda i, y, x : T.grad(grad_y[i], x),
                         sequences=T.arange(grad_y.shape[0]), non_sequences=[grad_y, x])
h = theano.function([x], H, updates=updates)
h([0, 0])

array([[ 2.,  0.],
       [ 0.,  2.]])