In [3]:
import theano
import theano.tensor as T
import numpy as np

In [4]:
X = T.matrix('X')
Y = T.matrix('Y')
b_sym = T.vector('b_sym')

results, updates = theano.scan(lambda v: T.tanh(T.dot(v, Y) + b_sym), sequences=X)
compute_elementwise = theano.function([X, Y, b_sym], results)

In [5]:
x = np.eye(2, dtype=theano.config.floatX)
y = np.ones((2, 2), dtype=theano.config.floatX)
b = np.ones((2), dtype=theano.config.floatX)
b[1] = 2

In [8]:
print compute_elementwise(x, y, b)
print np.tanh(np.dot(x, y) + b)

[[ 0.96402758  0.99505475]
 [ 0.96402758  0.99505475]]
[[ 0.96402758  0.99505475]
 [ 0.96402758  0.99505475]]


## Second example

In [12]:
rng = T.shared_randomstreams.RandomStreams(1234)
d = rng.binomial(size=Y[1].shape)

results, updates = theano.scan(lambda v: T.tanh(T.dot(v, Y) + b_sym) * d, sequences=d)
compute = theano.function([X, Y, b_sym], results, updates=updates, allow_input_downcast=True,
                          on_unused_input='ignore')

In [13]:
x = np.eye(10, 2, dtype=theano.config.floatX)
w = np.ones((2, 2), dtype=theano.config.floatX)
b = np.ones((2), dtype=theano.config.floatX)

compute(x, w, b)

array([[[ 0.96402758,  0.        ],
        [ 0.96402758,  0.        ]],

       [[ 0.        ,  0.76159416],
        [ 0.        ,  0.76159416]]])